name: Node Continuous Integration

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3      
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
    
      - name: Clean install packages
        run: npm ci

      - name: Run all automated tests
        run: npm test
      
      - name: Build and export
        run: npm run build
    