import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Index.module.scss';

const Index: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>PokeFight</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        hi
      </div>

    </div>
  )
}

export default Index;
