// Next
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';

// React and Styling
import React, { useEffect, useState } from 'react';
import styles from '../styles/Game.module.scss';

// MUI
import { Snackbar } from '@mui/material';

// Interfaces
import PokedexMap from '../interfaces/PokedexMap';
import PokemonMap from '../interfaces/PokemonMap';
import GameSave from '../interfaces/GameSave';

// Game Functions
import getEnemy from '../gameFunctions/getEnemy';
import getGameSave from '../gameFunctions/getGameSave';
import enemyFainted from '../gameFunctions/enemyFainted';

// Components
import Navbar from '../components/navbar';
import Floors from '../components/floors';
import Enemy from '../components/enemy';

const Game: NextPage = () => {
  const router = useRouter();

  const [clickDamage, setClickDamage] = useState(100);
  const [DPS, setDPS] = useState(1);
  const [floor, setFloor] = useState(0);
  const [highestFloor, setHighestFloor] = useState(1);
  const [items, setItems] = useState({});
  const [artwork, setArtwork] = useState('');
  const [storage, setStorage] = useState({});
  const [currency, setCurrency] = useState(0);
  const [team, setTeam] = useState<PokedexMap>({});
  const [badges, setBadges] = useState<string[]>([]);
  const [pokedex, setPokedex] = useState<PokedexMap>({});

  const [showAlert, setShowAlert] = useState(false);
  const [alerts, setAlerts] = useState<string[]>([]);

  const [enemy, setEnemy] = useState<PokemonMap>();
  const [enemiesLeft, setEnemiesLeft] = useState(10);
  const [discoveredPokemon, setDiscoveredPokemon] = useState<string[]>([]);

  useEffect(() => {
    if (!router) return;

    const gameUnlocks = JSON.parse(localStorage.getItem('gameUnlocked') || '{}');
    const game: GameSave | boolean = getGameSave();
    if (typeof game === "boolean") {
      router.push("/");
      return;
    } 
    
    setTeam(game.team);
    setItems(game.items);
    setFloor(game.floor);
    setBadges(game.badges);
    setPokedex(game.pokedex);
    setStorage(game.storage);
    setCurrency(game.currency);
    setDiscoveredPokemon(gameUnlocks.discoveredPokemon);
    setArtwork(localStorage.getItem('artwork') || 'official');
  }, [router]);

  useEffect(() => {
    if (pokedex === {} || floor === 0) return;

    const enemyInfo = getEnemy(pokedex, floor);
    setEnemy(enemyInfo);

    const enemyName = enemyInfo.name;
    if (!discoveredPokemon.includes(enemyName)) {
      setDiscoveredPokemon(discovered => [...discovered, enemyName]);
      setAlerts(alerts => [...alerts, enemyName.toUpperCase() + " added to the pokedex."]);
    }

    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [pokedex, enemiesLeft]);

  useEffect(() => {
    setEnemiesLeft(10);
    setHighestFloor(highestFloor => Math.max(floor, highestFloor));
  }, [floor])

  useEffect(() => {
    if (alerts.length === 0) setShowAlert(false);
    if (alerts.length >= 1) setShowAlert(true);
  }, [alerts.length])

  const nextEnemy = () => {
    if (enemy === undefined) return;

    if (enemiesLeft === 1) {
      setFloor(floor + 1);
    } else {
      // level ups, enemy joining team, and evolutions
      const newTeam = enemyFainted(team, pokedex, enemy);
      setTeam(newTeam);

      // calculate currency and get the next enemy
      setCurrency(currency => currency + Math.floor(enemy.level * ((enemy.stats[1] + enemy.statBoosts[0]) / 50) + floor));
      setEnemiesLeft(enemiesLeft => enemiesLeft - 1);
    }
  }

  const closeSnackbar = (_: React.SyntheticEvent | Event, reason?: string) => {
    if (reason === "clickaway") return;
    setShowAlert(false);
    setAlerts(alerts => alerts.slice(1));
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>HeroPokemon - A Pokemon-Based Idle Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar 
        currency={currency} 
        items={items} 
        storage={storage} 
        team={team} 
        badges={badges} 
        artwork={artwork}
      >
      </Navbar>

      <Snackbar 
        open={showAlert}
        message={alerts[0]}
        autoHideDuration={2000}
        onClose={closeSnackbar}
        anchorOrigin={{vertical: 'bottom', horizontal: 'right'}}
      ></Snackbar>


      <div className={styles.column}>
        <Floors floor={floor} setFloor={setFloor} highestFloor={highestFloor}></Floors>
        <strong className={styles.enemiesLeft}>{enemiesLeft + " wild pokemon left."}</strong>  
        <button onClick={() => setDPS(DPS => DPS + 1)} style={{width: "fit-content", height: "fit-content"}}>INCREASE DPS: {DPS}</button>
        <p>{floor + " --> " + highestFloor}</p>

        {enemy !== undefined && 
          <Enemy 
            enemy={enemy} 
            nextEnemy={nextEnemy} 
            clickDamage={clickDamage} 
            dps={DPS}
            artwork={artwork}
          >
          </Enemy>
        }
      </div>

    </div>
  )
}

export default Game;