name: Node Continuous Integration

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ] 

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3      
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
    
      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Install dependencies
        run: pnpm install

      # - name: Run all automated tests
      #   run: pnpm test
      
      - name: Build and export
        run: pnpm run build
    